Testing handler ResponseOk and ResponseError accepting an optional matcher
s7techlab/cckit pull request #51
Opened 2020-09-15 14:34 UTC by czar0

Replaced the optional `string` input with a more generic `OmegaMatcher` in order to provide more flexibility to the end-user for handling more complex case scenarios.

2021-03-04 16:07 UTC, czar0 commented
Hi @vitiko - Is there any chance we can discuss this PR? We have been using cckit for while and we love the way in which it is designed. We think this simple addition to the test cases could help in giving even more flexibility when errors are wrapped or stack-traced. Let me know what your thoughts are. We would be happy to contribute!

2021-03-05 07:16 UTC, vitiko requested changes
> Hi @vitiko - Is there any chance we can discuss this PR? We have been using cckit for while and we love the way in which it is designed. We think this simple addition to the test cases could help in giving even more flexibility when errors are wrapped or stack-traced. Let me know what your thoughts are. We would be happy to contribute!

Sorry, my previous answer remained in a pending state

very useful improvement, but i suggest to pass `okMatcher ...interface{}` to `responseOk` and `responseError` functions, instead of `okMatcher ...OmegaMatcher`

If okMatcher is a string - use it as default ContainSubstring matcher, if matcher is OmegaMatcher - use as OmegaMatcher, otherwise - fire error. It allows using all previous tests without changes.

2021-03-05 10:44 UTC, czar0 commented on testing/expect/response.go
> -func ResponseOk(response peer.Response, okSubstr ...string) peer.Response {
It makes sense, avoiding breaking changes 👍

2021-03-05 14:18 UTC, czar0 commented on testing/expect/response.go
> -func ResponseOk(response peer.Response, okSubstr ...string) peer.Response {
@vitiko changed made as requested. Have a look and see if they match what you had in mind.

2021-03-07 10:42 UTC, vitiko approved these changes

2021-03-07 10:42 UTC, merged